[package]
name = "embedded-keypad"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html


[dependencies]
bitmask-enum = "2.0.1"
embedded-hal = {version = "0.2.7", features = ["unproven"]}
defmt = "0.3.2"
paste = "1.0.9"